// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SkillCardData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static SkillCardData GetRootAsSkillCardData(ByteBuffer _bb) { return GetRootAsSkillCardData(_bb, new SkillCardData()); }
  public static SkillCardData GetRootAsSkillCardData(ByteBuffer _bb, SkillCardData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SkillCardData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Skillidx { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateSkillidx(int skillidx) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, skillidx); return true; } else { return false; } }
  public int Skillevel { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateSkillevel(int skillevel) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, skillevel); return true; } else { return false; } }
  public int Skillcount { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateSkillcount(int skillcount) { int o = __p.__offset(8); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, skillcount); return true; } else { return false; } }

  public static Offset<BanpoFri.Data.SkillCardData> CreateSkillCardData(FlatBufferBuilder builder,
      int skillidx = 0,
      int skillevel = 0,
      int skillcount = 0) {
    builder.StartTable(3);
    SkillCardData.AddSkillcount(builder, skillcount);
    SkillCardData.AddSkillevel(builder, skillevel);
    SkillCardData.AddSkillidx(builder, skillidx);
    return SkillCardData.EndSkillCardData(builder);
  }

  public static void StartSkillCardData(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddSkillidx(FlatBufferBuilder builder, int skillidx) { builder.AddInt(0, skillidx, 0); }
  public static void AddSkillevel(FlatBufferBuilder builder, int skillevel) { builder.AddInt(1, skillevel, 0); }
  public static void AddSkillcount(FlatBufferBuilder builder, int skillcount) { builder.AddInt(2, skillcount, 0); }
  public static Offset<BanpoFri.Data.SkillCardData> EndSkillCardData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.SkillCardData>(o);
  }
  public SkillCardDataT UnPack() {
    var _o = new SkillCardDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SkillCardDataT _o) {
    _o.Skillidx = this.Skillidx;
    _o.Skillevel = this.Skillevel;
    _o.Skillcount = this.Skillcount;
  }
  public static Offset<BanpoFri.Data.SkillCardData> Pack(FlatBufferBuilder builder, SkillCardDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.SkillCardData>);
    return CreateSkillCardData(
      builder,
      _o.Skillidx,
      _o.Skillevel,
      _o.Skillcount);
  }
}

public class SkillCardDataT
{
  [Newtonsoft.Json.JsonProperty("skillidx")]
  public int Skillidx { get; set; }
  [Newtonsoft.Json.JsonProperty("skillevel")]
  public int Skillevel { get; set; }
  [Newtonsoft.Json.JsonProperty("skillcount")]
  public int Skillcount { get; set; }

  public SkillCardDataT() {
    this.Skillidx = 0;
    this.Skillevel = 0;
    this.Skillcount = 0;
  }
}


static public class SkillCardDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Skillidx*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Skillevel*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Skillcount*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
